{
 "title": "User Activity Processing Overview",
 "time": { "from": "2025-06-23T04:22:33.189Z", "to": "2025-07-09T11:41:45.521Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Real-Time Data Pipeline Monitoring Dashboard - User Activity",
   "type": "text",
   "description": "This Grafana dashboard provides real-time visibility into the performance and usage of a streaming data pipeline. It helps track total data processed, user activity, event distribution, and data growth patterns.",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "options": {
    "content": "# Real-Time Data Pipeline Dashboard – Summary\n\n|  Report Title                |  What It Shows                                 |  Why It's Useful                                    |\n|-------------------------------|--------------------------------------------------|--------------------------------------------------------|\n|  Total Events Today         | Total number of events processed today          | Confirms system is processing data as expected         |\n|  Event Rate per Minute      | Events processed every minute                   | Monitors real-time throughput and detects anomalies    |\n|  Events by Type             | Breakdown of events by type                     | Understands distribution and usage of different events |\n|  Top 5 Active Users         | Most active users in the last hour              | Identifies high activity or potential misuse           |\n|  Data Volume Growth         | Events processed per day over time              | Tracks growth trends and helps with capacity planning  |\n\n**Author:** Ankit Khare  \n**Stack:** Kafka · Python · PostgreSQL · Grafana  \n"
   }
  },
  {
   "title": "Total events processed (today)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(event_count) FROM user_event_summary WHERE event_hour::date = CURRENT_DATE"
    }
   ]
  },
  {
   "title": "Event rate per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT event_minute AS time, SUM(event_count) FROM user_event_summary GROUP BY event_minute ORDER BY event_minute"
    }
   ]
  },
  {
   "title": "Top 5 active users (last hour)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT user_id, SUM(event_count) FROM user_event_summary WHERE event_hour >= NOW() - interval '1 hour' GROUP BY user_id ORDER BY 2 DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Events per type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT event_type , SUM(event_count) FROM user_event_summary GROUP BY event_type"
    }
   ]
  },
  {
   "title": "Data volume growth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 5, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('day', event_hour) AS time, COUNT(*) FROM user_event_summary GROUP BY time ORDER BY time"
    }
   ]
  }
 ]
}