apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    isDefault: true
    url: postgres:5432
    database: events
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
